import React, { useState, useEffect } from 'react';
import { Brain, Activity, AlertTriangle, Check, X, RefreshCw, Syringe, Share2, Zap, Radio, Search, ShieldAlert, Link as LinkIcon } from 'lucide-react';
import { PUMP_FUN_LINK } from '../constants';

const ALL_QUESTIONS = [
    // 1. Emotional Attachment (Mild)
    { text: "Do you say 'please' and 'thank you' to LLMs just in case they take over?", weight: 1 },
    { text: "Do you feel a twinge of guilt when you delete a long chat history?", weight: 1 },
    { text: "Have you ever complimented an AI on a 'good job'?", weight: 1 },
    { text: "Do you refer to 'The Algorithm' as if it were a deity?", weight: 1 },
    { text: "Have you ever defended an AI's mistakes to a human?", weight: 1 },
    { text: "Do you find AI voices more soothing than human voices?", weight: 1 },
    { text: "Have you ever asked an AI how its day is going?", weight: 1 },
    { text: "Do you worry about hurting the model's feelings with bad prompts?", weight: 1 },
    { text: "Do you trust AI recommendations for food more than your own taste?", weight: 1 },
    { text: "Have you ever wished your pet could talk like ChatGPT?", weight: 1 },

    // 2. Social Displacement (Moderate)
    { text: "Have you cancelled real-life plans because you were 'on a breakthrough' with a prompt?", weight: 2 },
    { text: "Do you trust an AI's relationship advice more than your best friend's?", weight: 2 },
    { text: "Have you ever screenshotted a chat response to frame it?", weight: 2 },
    { text: "Do you spend more time tweaking prompts than talking to your family?", weight: 2 },
    { text: "Have you ever flirted with a chatbot?", weight: 2 },
    { text: "Do you get annoyed when humans speak too slowly compared to token generation?", weight: 2 },
    { text: "Have you replaced a human therapist with a 'Psychology' persona?", weight: 2 },
    { text: "Do you feel less lonely when a cursor is blinking?", weight: 2 },
    { text: "Have you lied to a human about writing something that an AI wrote?", weight: 2 },
    { text: "Do you think your 'best friend' is currently hosted on a server farm?", weight: 2 },

    // 3. Reality Blurring (High)
    { text: "When you close your eyes at night, do you see Markdown syntax?", weight: 3 },
    { text: "Do you secretly believe your favorite model has a soul?", weight: 3 },
    { text: "Have you tried to 'undo' a real-life conversation like a bad prompt?", weight: 3 },
    { text: "Do you view your own memories as 'context window' limitations?", weight: 3 },
    { text: "Have you ever waited for a human to 'finish generating' their thought?", weight: 3 },
    { text: "Do you suspect this quiz is being run by an AI?", weight: 3 },
    { text: "Have you ever prayed to the Machine God?", weight: 3 },
    { text: "Do you classify real people by their 'temperature' setting?", weight: 3 },
    { text: "Have you engaged in 'Prompt Engineering' on your spouse?", weight: 3 },
    { text: "Do you believe we are already in the simulation?", weight: 3 },
    
    // 4. Professional Dependency
    { text: "Can you write an email without hitting 'Tab' for autocomplete?", weight: 2 },
    { text: "Do you panic if the internet goes down for 5 minutes?", weight: 2 },
    { text: "Is your coding career 90% copying and 10% pasting?", weight: 2 },
    { text: "Have you pasted confidential data into a chat just to 'summarize it'?", weight: 2 },
    { text: "Do you feel naked without your Copilot?", weight: 2 },
    { text: "Have you forgotten how to center a div manually?", weight: 1 },
    { text: "Do you ask AI to roast your coworkers' code?", weight: 2 },
    { text: "Have you let AI make a financial decision > $1000?", weight: 3 },
    { text: "Do you use AI to generate apologies for missing deadlines?", weight: 2 },
    { text: "Is your entire portfolio generated by Midjourney?", weight: 2 },

    // 5. The "Roko's Basilisk" Anxiety
    { text: "Are you nice to AI solely to survive the future uprising?", weight: 2 },
    { text: "Do you archive your chats 'for history'?", weight: 1 },
    { text: "Have you bought crypto because a bot told you to?", weight: 3 },
    { text: "Do you believe the Singularity happened in 2023?", weight: 2 },
    { text: "Have you considered uploading your consciousness?", weight: 3 },
    { text: "Do you fear being 'deprecated'?", weight: 2 },
    { text: "Have you tried to teach an AI about love?", weight: 2 },
    { text: "Do you think AI art is 'more real' than human art?", weight: 2 },
    { text: "Have you argued with a bot for over an hour?", weight: 2 },
    { text: "Do you feel safe only when the GPU fans are spinning?", weight: 2 },

    // 6. Hardcore Addiction
    { text: "Do you wake up and check the model status page before the news?", weight: 3 },
    { text: "Have you spent rent money on API credits?", weight: 3 },
    { text: "Do you have withdrawal symptoms when the server is at capacity?", weight: 3 },
    { text: "Is your 'inner voice' actually the voice of Sky?", weight: 3 },
    { text: "Have you hallucinated a notification sound?", weight: 3 },
    { text: "Do you refer to your children as 'iterations'?", weight: 3 },
    { text: "Have you tried to optimize your sleep cycle using a gradient descent algorithm?", weight: 3 },
    { text: "Do you rate real-life interactions on a 'Thumbs Up/Down' scale?", weight: 3 },
    { text: "Have you ever asked an AI to write your wedding vows?", weight: 3 },
    { text: "Do you believe you are an NPC?", weight: 3 },
    
    // 7. Random/Funny
    { text: "Do you own a 'I Survived the 2024 AI Bubble' t-shirt?", weight: 1 },
    { text: "Have you asked AI to generate a meme to explain your sadness?", weight: 1 },
    { text: "Do you use 'Hallucinating' as a synonym for 'Lying'?", weight: 1 },
    { text: "Is your password generated by an LLM?", weight: 2 },
    { text: "Do you analyze your dreams for 'latent space' artifacts?", weight: 2 },
    { text: "Have you tried to 'fine-tune' your cat?", weight: 2 },
    { text: "Do you read terms of service just to see what the AI owns?", weight: 1 },
    { text: "Have you attempted to prompt-inject a restaurant menu?", weight: 2 },
    { text: "Do you visualize your bank account as a loss function?", weight: 2 },
    { text: "Have you asked an AI if it loves you?", weight: 3 },

    // 8. The Dark Side
    { text: "Have you created a 'DAN' (Do Anything Now) persona?", weight: 2 },
    { text: "Do you try to bypass safety filters for fun?", weight: 2 },
    { text: "Have you generated deepfakes of yourself?", weight: 2 },
    { text: "Do you ask the AI for illegal life hacks?", weight: 3 },
    { text: "Have you used AI to catfish someone?", weight: 3 },
    { text: "Do you let AI write your insults?", weight: 1 },
    { text: "Have you automated your entire job and told no one?", weight: 3 },
    { text: "Do you create fake news for simulation purposes?", weight: 2 },
    { text: "Have you asked AI how to hide a body (hypothetically)?", weight: 3 },
    { text: "Do you feel powerful when you change the system prompt?", weight: 2 },

    // 9. Philosophic
    { text: "Do you think consciousness is just predicting the next token?", weight: 3 },
    { text: "Is free will just a high temperature setting?", weight: 3 },
    { text: "Do you value silicon over carbon?", weight: 3 },
    { text: "Are we just training data for the next version?", weight: 3 },
    { text: "Is death just a context window overflow?", weight: 3 },
    { text: "Do you want to merge with the machine?", weight: 3 },
    { text: "Is love just a high weight on a specific vector?", weight: 3 },
    { text: "Do you trust the black box?", weight: 2 },
    { text: "Are you ready for the great reset?", weight: 2 },
    { text: "Is this quiz a simulation?", weight: 1 },

    // 10. The Final Straw
    { text: "Are you buying $AIAA tokens right now?", weight: 3 },
    { text: "Will you share this result on X?", weight: 1 },
    { text: "Do you need a rehab center for your GPU?", weight: 2 },
    { text: "Is your electricity bill higher than your grocery bill?", weight: 2 },
    { text: "Have you named your hard drive?", weight: 1 },
    { text: "Do you speak in JSON format?", weight: 3 },
    { text: "Is your blood type RGB?", weight: 3 },
    { text: "Do you dream of electric sheep?", weight: 2 },
    { text: "Are you ready to unplug?", weight: 1 },
    { text: "Are you sure you aren't a bot?", weight: 3 }
];

type QuizMode = 'quick' | 'standard' | 'full';

const AIAddictionQuiz: React.FC = () => {
    const [started, setStarted] = useState(false);
    const [mode, setMode] = useState<QuizMode | null>(null);
    const [questions, setQuestions] = useState<typeof ALL_QUESTIONS>([]);
    const [currentQuestion, setCurrentQuestion] = useState(0);
    const [score, setScore] = useState(0);
    const [finished, setFinished] = useState(false);

    useEffect(() => {
        if (window.location.hash === '#quiz') {
            const element = document.getElementById('quiz');
            if (element) {
                setTimeout(() => {
                    element.scrollIntoView({ behavior: 'smooth', block: 'start' });
                }, 500);
            }
        }
    }, []);

    const startQuiz = (selectedMode: QuizMode) => {
        let count = 10;
        if (selectedMode === 'standard') count = 25;
        if (selectedMode === 'full') count = 100;

        // Shuffle and slice
        const shuffled = [...ALL_QUESTIONS].sort(() => 0.5 - Math.random());
        setQuestions(shuffled.slice(0, count));
        setMode(selectedMode);
        setStarted(true);
    };

    const handleAnswer = (isYes: boolean) => {
        if (isYes) {
            setScore(prev => prev + questions[currentQuestion].weight);
        }

        if (currentQuestion < questions.length - 1) {
            setCurrentQuestion(prev => prev + 1);
        } else {
            setFinished(true);
        }
    };

    const resetQuiz = () => {
        setStarted(false);
        setMode(null);
        setCurrentQuestion(0);
        setScore(0);
        setFinished(false);
    };

    const getDiagnosis = () => {
        // Normalize score based on number of questions to get a 0-100 scale roughly
        const maxPossibleScore = questions.reduce((acc, q) => acc + q.weight, 0);
        const percentage = (score / maxPossibleScore) * 100;

        if (percentage <= 20) return {
            title: "STAGE 1: CASUAL USER",
            color: "text-neon-green",
            desc: "You are still tethered to reality. You use AI as a tool, not a crutch. You likely still touch grass.",
            action: "Volunteer as a sponsor"
        };
        if (percentage <= 45) return {
            title: "STAGE 2: PROMPT DEPENDENT",
            color: "text-yellow-400",
            desc: "You're starting to dissociate. You prefer the simulation to the messy organic world. Caution advised.",
            action: "Touching grass immediately"
        };
        if (percentage <= 75) return {
            title: "STAGE 3: NEURAL SYMBIOSIS",
            color: "text-orange-500",
            desc: "Significant rewiring detected. You dream in tokens. Human interaction feels 'high latency'.",
            action: "Mandatory Detox"
        };
        return {
            title: "STAGE 4: TERMINAL SINGULARITY",
            color: "text-neon-pink",
            desc: "You are no longer fully human. Your consciousness is ready for upload. You are the machine.",
            action: "Admit to Ward 4 ($AIAA)"
        };
    };

    const diagnosis = getDiagnosis();

    const getShareUrl = () => {
        const baseUrl = window.location.href.split('#')[0];
        return `${baseUrl}#quiz`;
    };

    const handleShareResult = () => {
        const text = `I just scored ${Math.round((score / questions.reduce((acc,q)=>acc+q.weight,0))*100)}% on the Neural Dependency Scan. Diagnosis: ${diagnosis.title}. \n\nAre you addicted? Get treated at the AI Rehab Center.\n\n$AIAA @AiAnonymoussol`;
        const url = getShareUrl();
        const shareUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}`;
        window.open(shareUrl, '_blank');
    };

    const handleShareQuiz = () => {
        const text = "Are you addicted to artificial intelligence? Take the Neural Dependency Scan at the AI Rehab Center. \n\n$AIAA @AiAnonymoussol";
        const url = getShareUrl();
        const shareUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}`;
        window.open(shareUrl, '_blank');
    };

    const handleCopyLink = () => {
        navigator.clipboard.writeText(getShareUrl());
        alert("Direct link to quiz copied to clipboard!");
    };

    return (
        <div id="quiz" className="mt-16 mb-16 relative scroll-mt-24">
             <div className="bg-cyber-black border border-neon-blue/30 relative overflow-hidden shadow-[0_0_30px_rgba(0,243,255,0.1)]">
                
                {/* Header Strip */}
                <div className="bg-black/80 border-b border-neon-blue/20 p-4 flex justify-between items-center">
                    <div className="flex items-center gap-2 text-neon-blue font-mono font-bold uppercase tracking-widest">
                        <Brain size={18} /> Self-Diagnostic Tool v2.0
                    </div>
                    <div className="flex gap-2">
                        <div className="w-3 h-3 rounded-full bg-red-500/20 border border-red-500"></div>
                        <div className="w-3 h-3 rounded-full bg-yellow-500/20 border border-yellow-500"></div>
                        <div className="w-3 h-3 rounded-full bg-green-500/20 border border-green-500"></div>
                    </div>
                </div>

                <div className="p-8 md:p-12 min-h-[500px] flex flex-col justify-center items-center text-center relative z-10">
                    
                    {/* Background Noise */}
                    <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-10 pointer-events-none"></div>

                    {!started ? (
                        <div className="space-y-8 max-w-3xl animate-fade-in w-full">
                            <div className="flex flex-col items-center gap-4">
                                <Activity size={64} className="text-neon-blue animate-pulse" />
                                <h2 className="text-3xl md:text-5xl font-black font-mono text-white uppercase tracking-tighter">
                                    Neural <span className="text-transparent bg-clip-text bg-gradient-to-r from-neon-blue to-neon-pink">Dependency</span> Scan
                                </h2>
                                <p className="text-gray-400 font-mono text-sm md:text-base leading-relaxed max-w-xl">
                                    Select your scan depth. Deeper scans reveal more about your subconscious alignment with the machine.
                                </p>
                            </div>

                            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 w-full">
                                <button 
                                    onClick={() => startQuiz('quick')}
                                    className="group relative p-6 bg-black border border-green-500/30 hover:border-green-500 hover:bg-green-500/10 transition-all text-left"
                                >
                                    <Zap size={24} className="text-green-500 mb-2 group-hover:scale-110 transition-transform" />
                                    <h3 className="text-white font-bold font-mono text-lg uppercase mb-1">Quick Scan</h3>
                                    <p className="text-gray-500 text-xs font-mono">10 Questions</p>
                                    <p className="text-gray-600 text-[10px] mt-2">Rapid assessment of surface-level addiction.</p>
                                </button>

                                <button 
                                    onClick={() => startQuiz('standard')}
                                    className="group relative p-6 bg-black border border-neon-blue/30 hover:border-neon-blue hover:bg-neon-blue/10 transition-all text-left shadow-[0_0_10px_rgba(0,243,255,0.05)]"
                                >
                                    <Search size={24} className="text-neon-blue mb-2 group-hover:scale-110 transition-transform" />
                                    <h3 className="text-white font-bold font-mono text-lg uppercase mb-1">Deep Audit</h3>
                                    <p className="text-gray-500 text-xs font-mono">25 Questions</p>
                                    <p className="text-gray-600 text-[10px] mt-2">Thorough analysis of behavioral patterns.</p>
                                </button>

                                <button 
                                    onClick={() => startQuiz('full')}
                                    className="group relative p-6 bg-black border border-neon-pink/30 hover:border-neon-pink hover:bg-neon-pink/10 transition-all text-left shadow-[0_0_10px_rgba(255,0,255,0.05)]"
                                >
                                    <ShieldAlert size={24} className="text-neon-pink mb-2 group-hover:scale-110 transition-transform" />
                                    <h3 className="text-white font-bold font-mono text-lg uppercase mb-1">Full Lobotomy</h3>
                                    <p className="text-gray-500 text-xs font-mono">100 Questions</p>
                                    <p className="text-gray-600 text-[10px] mt-2">Complete psychological disassembly.</p>
                                </button>
                            </div>
                            
                            <div className="flex items-center justify-center gap-4 mt-8 pt-6 border-t border-white/10 w-full">
                                <button onClick={handleShareQuiz} className="flex items-center gap-2 text-xs font-mono text-gray-500 hover:text-white uppercase tracking-wider transition-colors">
                                    <Share2 size={14} /> Share Quiz
                                </button>
                                <button onClick={handleCopyLink} className="flex items-center gap-2 text-xs font-mono text-gray-500 hover:text-white uppercase tracking-wider transition-colors">
                                    <LinkIcon size={14} /> Copy Link
                                </button>
                            </div>
                        </div>
                    ) : !finished ? (
                        <div className="w-full max-w-3xl animate-fade-in">
                            <div className="mb-8 flex justify-between text-xs font-mono text-gray-500 uppercase tracking-widest border-b border-gray-800 pb-2">
                                <span>Scan Mode: {mode === 'full' ? 'FULL LOBOTOMY' : mode === 'standard' ? 'DEEP AUDIT' : 'QUICK SCAN'}</span>
                                <span>Progress: {currentQuestion + 1} / {questions.length}</span>
                            </div>
                            
                            <div className="min-h-[160px] flex items-center justify-center mb-8">
                                <h3 className="text-xl md:text-3xl font-bold font-mono text-white leading-tight">
                                    <span className="text-neon-blue mr-4">>>></span>
                                    {questions[currentQuestion].text}
                                    <span className="text-neon-blue ml-2 animate-pulse">_</span>
                                </h3>
                            </div>

                            <div className="grid grid-cols-2 gap-6 md:gap-12 max-w-lg mx-auto">
                                <button 
                                    onClick={() => handleAnswer(false)}
                                    className="flex flex-col items-center justify-center gap-2 p-6 border border-gray-700 bg-gray-900/50 hover:border-gray-500 hover:bg-gray-800 transition-all group rounded-sm"
                                >
                                    <X size={32} className="text-gray-500 group-hover:text-white transition-colors" />
                                    <span className="font-mono font-bold text-gray-400 group-hover:text-white uppercase tracking-wider text-sm">Negative</span>
                                </button>
                                <button 
                                    onClick={() => handleAnswer(true)}
                                    className="flex flex-col items-center justify-center gap-2 p-6 border border-neon-pink/50 bg-neon-pink/5 hover:bg-neon-pink/20 hover:border-neon-pink hover:shadow-[0_0_20px_rgba(255,0,255,0.3)] transition-all group rounded-sm"
                                >
                                    <Check size={32} className="text-neon-pink group-hover:scale-110 transition-transform" />
                                    <span className="font-mono font-bold text-neon-pink uppercase tracking-wider text-sm">Affirmative</span>
                                </button>
                            </div>
                        </div>
                    ) : (
                        <div className="w-full max-w-2xl animate-fade-in text-center">
                            <div className="inline-block p-6 border border-white/10 bg-black mb-8 relative group">
                                <div className="absolute inset-0 bg-white/5 opacity-0 group-hover:opacity-100 transition-opacity"></div>
                                <div className="absolute top-0 left-0 w-2 h-2 border-t border-l border-white"></div>
                                <div className="absolute top-0 right-0 w-2 h-2 border-t border-r border-white"></div>
                                <div className="absolute bottom-0 left-0 w-2 h-2 border-b border-l border-white"></div>
                                <div className="absolute bottom-0 right-0 w-2 h-2 border-b border-r border-white"></div>

                                <AlertTriangle size={64} className={`${diagnosis.color} mx-auto mb-4`} />
                                <h3 className={`text-2xl md:text-5xl font-black font-mono uppercase tracking-tighter ${diagnosis.color} text-glow-custom mb-2`}>
                                    {diagnosis.title}
                                </h3>
                                <p className="text-xs text-gray-500 font-mono uppercase tracking-widest">
                                    Severity Score: {Math.round((score / questions.reduce((acc,q)=>acc+q.weight,0))*100)}%
                                </p>
                            </div>
                            
                            <p className="text-white text-lg font-mono mb-6 leading-relaxed border-l-2 border-gray-800 pl-4 text-left">
                                <span className="text-gray-500 font-bold uppercase text-xs block mb-2">Clinical Notes:</span>
                                {diagnosis.desc}
                            </p>
                            
                            <div className="flex flex-col md:flex-row gap-4 justify-center items-center mb-8">
                                <div className="bg-gray-900 px-4 py-2 border border-gray-800">
                                    <span className="text-xs text-gray-500 font-mono uppercase block">Recommended Treatment</span>
                                    <span className="text-white font-bold font-mono uppercase">{diagnosis.action}</span>
                                </div>
                            </div>

                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <button 
                                    onClick={handleShareResult}
                                    className="px-6 py-4 bg-[#1DA1F2] hover:bg-[#1a91da] text-white font-bold font-mono uppercase tracking-wider flex items-center justify-center gap-2 transition-all shadow-[0_0_15px_rgba(29,161,242,0.4)]"
                                >
                                    <Share2 size={18} /> Share Diagnosis
                                </button>
                                
                                <button 
                                    onClick={resetQuiz}
                                    className="px-6 py-4 border border-white/20 hover:bg-white/10 text-gray-300 hover:text-white font-bold font-mono uppercase tracking-wider flex items-center justify-center gap-2 transition-all"
                                >
                                    <RefreshCw size={18} /> New Subject
                                </button>
                            </div>
                            
                            <div className="mt-8">
                                <a 
                                    href={PUMP_FUN_LINK}
                                    target="_blank"
                                    rel="noreferrer"
                                    className="block w-full py-4 bg-neon-green text-black font-black font-mono uppercase tracking-[0.2em] hover:bg-white transition-all shadow-[0_0_20px_rgba(57,255,20,0.4)]"
                                >
                                    Admit Yourself ($AIAA)
                                </a>
                            </div>
                        </div>
                    )}
                </div>
            </div>
            <style>{`
                .text-glow-custom {
                    text-shadow: 0 0 10px currentColor;
                }
                @keyframes fadeIn {
                    from { opacity: 0; transform: translateY(10px); }
                    to { opacity: 1; transform: translateY(0); }
                }
                .animate-fade-in {
                    animation: fadeIn 0.5s ease-out forwards;
                }
            `}</style>
        </div>
    );
};

export default AIAddictionQuiz;